// kx_skia_wasm.cpp — WASM (emscripten) platform implementation: Ganesh WebGL2
// onscreen backend (CanvasKit FBO-0 pattern, modules/canvaskit/canvaskit_bindings.cpp:288-320)
// + embedded font manager. Implements kx_skia_platform.h for wasm32-emscripten.
//
// Build (build.zig wasm target): emcc via zig cc, flags
// -std=c++20 -fno-exceptions -fno-rtti -DSK_GANESH -DSK_GL
// -DSK_FORCE_8_BYTE_ALIGNMENT + the emsdk sysroot include path (for
// <GLES3/gl32.h>). Include roots: kx_skia/include, deps/skia, deps/skia/include,
// deps/SDL/include.
//
// The browser owns the main thread (rAF loop in src/platform_wasm.zig):
// gpu_end_frame only submits + SDL_GL_SwapWindow — the compositor presents
// when the rAF callback returns (no preserveDrawingBuffer needed).
#include "kx_skia_platform.h"

#include <SDL3/SDL.h>

#include <GLES3/gl32.h> // emscripten sysroot (WebGL2); glBindFramebuffer

#include "include/core/SkColorSpace.h"
#include "include/core/SkImageInfo.h"
#include "include/core/SkSurface.h"
#include "include/gpu/ganesh/GrDirectContext.h"
#include "include/gpu/ganesh/GrTypes.h"                 // kBottomLeft_GrSurfaceOrigin, k*_GrGLBackendState, GrSyncCpu
#include "include/gpu/ganesh/SkSurfaceGanesh.h"         // SkSurfaces::WrapBackendRenderTarget
#include "include/gpu/ganesh/gl/GrGLBackendSurface.h"    // GrBackendRenderTargets::MakeGL
#include "include/gpu/ganesh/gl/GrGLDirectContext.h"     // GrDirectContexts::MakeGL
#include "include/gpu/ganesh/gl/GrGLInterface.h"
#include "include/gpu/ganesh/gl/GrGLMakeWebGLInterface.h" // GrGLInterfaces::MakeWebGL
#include "include/gpu/ganesh/gl/GrGLTypes.h"             // GrGLFramebufferInfo
#include "src/gpu/ganesh/gl/GrGLDefines.h"               // GR_GL_RGBA8 (same private include as canvaskit_bindings.cpp)
#include "include/ports/SkFontMgr_empty.h"

#include <cstddef>
#include <cstdint>

// --- Embedded default font ---
//
// kx_font_wasm.h is generated by scripts/fetch-deps.sh (web-wasm tag), next to
// this file (kx_skia/src/) or on the shim include path. Contract:
//   static const unsigned char kKxDefaultFontData[] = { ...ttf/otf bytes... };
//   static const size_t kKxDefaultFontSize = sizeof(kKxDefaultFontData);
// Until it lands, the stub keeps the shim compiling and platform_font_mgr()
// falls back to an empty font manager (metrics work, no glyphs).
#if __has_include("kx_font_wasm.h")
#include "kx_font_wasm.h"
#else
static const unsigned char kKxDefaultFontData[] = {0};
static const size_t kKxDefaultFontSize = 0;
#endif

// SkFontMgr_New_Custom_Embedded has no public header in this Skia pin: the
// factory lives in src/ports/SkFontMgr_custom_embedded.cpp (built when
// skia_enable_fontmgr_custom_embedded=true — set in out/web-wasm/args.gn).
// The structs below mirror that .cpp exactly; identical names → identical
// C++ mangling → links against libskia.wasm.a.
#if __has_include("include/ports/SkFontMgr_custom.h")
#include "include/ports/SkFontMgr_custom.h"
#else
struct SkEmbeddedResource { const uint8_t* data; size_t size; };
struct SkEmbeddedResourceHeader { const SkEmbeddedResource* entries; int count; };
sk_sp<SkFontMgr> SkFontMgr_New_Custom_Embedded(const SkEmbeddedResourceHeader* header);
#endif

namespace kx {

struct GpuState {
    SDL_Window* window = nullptr;
    sk_sp<GrDirectContext> dctx;
    sk_sp<SkSurface> frame_surface;
    int width = 0;
    int height = 0;
};

bool gpu_init(GpuState** out, void* sdl_window, int width, int height) {
    if (!out || !sdl_window) return false;
    // The caller (main, emscripten path) creates a WebGL2 context on the SDL
    // window and makes it current BEFORE kx_create. Ganesh binds to whatever
    // GL context is current — MakeWebGL links GLES3 statically (no
    // GetProcAddress), so the context must already be current here.
    if (!SDL_GL_GetCurrentContext()) return false;

    sk_sp<const GrGLInterface> interface = GrGLInterfaces::MakeWebGL();
    if (!interface) return false;
    sk_sp<GrDirectContext> dctx = GrDirectContexts::MakeGL(std::move(interface));
    if (!dctx) return false;

    auto* state = new GpuState();
    state->window = static_cast<SDL_Window*>(sdl_window);
    state->dctx = std::move(dctx);
    state->width = width;
    state->height = height;
    *out = state;
    return true;
}

void gpu_shutdown(GpuState* state) {
    if (!state) return;
    state->frame_surface = nullptr;
    if (state->dctx) {
        // Wait for in-flight GPU work before tearing the context down.
        state->dctx->flushAndSubmit(GrSyncCpu::kYes);
        state->dctx = nullptr;
    }
    delete state;
}

void gpu_resize(GpuState* state, int width, int height) {
    if (!state) return;
    // The onscreen target wraps FBO 0 and is re-created from these dimensions
    // on the next gpu_begin_frame.
    state->width = width;
    state->height = height;
}

SkCanvas* gpu_begin_frame(GpuState* state) {
    if (!state || !state->dctx || state->width <= 0 || state->height <= 0) return nullptr;

    // The onscreen canvas is FBO 0 (the WebGL default framebuffer). Make it
    // current and tell Skia its GL state is unknown (first frame / context
    // loss / browser state change).
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    state->dctx->resetContext(kRenderTarget_GrGLBackendState | kMisc_GrGLBackendState);

    // Wrap FBO 0 in a Skia backend render target (CanvasKit pattern).
    GrGLFramebufferInfo info;
    info.fFBOID = 0;
    info.fFormat = GR_GL_RGBA8;
    const GrBackendRenderTarget target = GrBackendRenderTargets::MakeGL(
        state->width, state->height, /*sampleCnt=*/0, /*stencilBits=*/8, info);
    state->frame_surface = SkSurfaces::WrapBackendRenderTarget(
        state->dctx.get(), target, kBottomLeft_GrSurfaceOrigin,
        kRGBA_8888_SkColorType, SkColorSpace::MakeSRGB(), nullptr);
    if (!state->frame_surface) return nullptr;
    return state->frame_surface->getCanvas();
}

void gpu_end_frame(GpuState* state) {
    if (!state || !state->dctx) return;
    state->dctx->flushAndSubmit();
    // Release the wrapped target before present: the drawing buffer is
    // composited by the browser when the rAF callback returns.
    state->frame_surface = nullptr;
    if (state->window) SDL_GL_SwapWindow(state->window);
}

sk_sp<SkFontMgr> platform_font_mgr() {
    if (kKxDefaultFontSize > 0) {
        const SkEmbeddedResource font = {kKxDefaultFontData, kKxDefaultFontSize};
        const SkEmbeddedResourceHeader header = {&font, 1};
        if (sk_sp<SkFontMgr> mgr = SkFontMgr_New_Custom_Embedded(&header)) {
            return mgr;
        }
    }
    return SkFontMgr_New_Custom_Empty();
}

} // namespace kx
